# Generated by Django 2.2.1 on 2020-05-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_auto_20200429_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_status', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='m_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
