# Generated by Django 2.2.1 on 2020-05-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_auto_20200502_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='m_move',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='m_turn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
