# Generated by Django 2.2.1 on 2020-05-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0004_auto_20200505_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='m_turn',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
