# Generated by Django 2.2.1 on 2020-05-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0005_auto_20200505_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
