# Generated by Django 2.2.1 on 2020-05-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0006_room_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date_created',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
