# Generated by Django 2.2.1 on 2020-05-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0007_room_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date_created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
