# Generated by Django 2.2.1 on 2020-05-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0009_auto_20200505_0353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterField(
            model_name='room',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
