# Generated by Django 2.2.1 on 2020-05-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0012_auto_20200505_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='m_draws',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='m_logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='player',
            name='m_loses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='m_wins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='m_stat',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
