# Generated by Django 2.2.1 on 2020-05-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0013_auto_20200508_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='m_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='m_send',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
