# Generated by Django 2.2.1 on 2020-05-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0014_auto_20200517_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='m_sender',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='m_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='m_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='m_admin_message',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='m_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
