# Generated by Django 3.0.6 on 2020-05-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0015_auto_20200520_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='m_send',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
