# Generated by Django 2.2.1 on 2020-05-25 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0015_auto_20200520_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_friends', models.ManyToManyField(blank=True, related_name='friends', to='chess.Player')),
                ('m_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='chess.Player')),
            ],
        ),
        migrations.DeleteModel(
            name='Creating',
        ),
        migrations.AlterField(
            model_name='room',
            name='m_send',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
