# Generated by Django 2.2.1 on 2020-05-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0016_auto_20200525_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='m_friends',
            field=models.ManyToManyField(blank=True, related_name='_player_m_friends_+', to='chess.Player'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
