# Generated by Django 3.0.6 on 2020-05-25 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0016_auto_20200521_0746'),
        ('chess', '0017_auto_20200525_1057'),
    ]

    operations = [
    ]
